[tool.poetry]
name = "docsy"
version = "0.1.0"
description = ""
authors = ["Felix Zieger <mail@felixzieger.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
slack-bolt = "^1.18.1"
openai = "^1.30.3"
gitpython = "^3.1.43"
pygithub = "^2.3.0"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
