"""create events table

Revision ID: 9d45975b880d
Revises: 4a60cab87218
Create Date: 2024-08-20 10:32:58.884270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d45975b880d"
down_revision: Union[str, None] = "4a60cab87218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("previous_content", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("team_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["customers.team_id"],
        ),
        sa.PrimaryKeyConstraint("created_on"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
